### ISSUE TITLE
C# Course Readme links broken

### ISSUE THREAD

**Issue by BSeyfi** [cs-internship/cs-internship-spec#111]
[C# course readme](https://github.com/cs-internship/cs-internship-spec/tree/master/courses/csharp) links to C# steps md files are broken. Please correct them.

**Comment by mehrandvd** [comment]
Thank you @BSeyfi.
@elldora can you put this on our backlogs for the next sprint?

**Comment by elldora** [comment]
Drear @BSeyfi

**Comment by mehrandvd** [comment]
Thank you @elldora 
All looks good, I'm closing this issue.

**Comment by BSeyfi** [comment]
Thank you @elldora , @mehrandvd
