### ISSUE TITLE
Updates according to the new rules for interns becoming mentors

### ISSUE THREAD

**Issue by Md23Mh** [cs-internship/cs-internship-spec#31]
The following documents need to be modified according to the new rules for assigning the mentorship task to interns:

https://github.com/cs-internship/cs-internship-spec/blob/master/meetings/meeting-entrance-interview.md
https://github.com/cs-internship/cs-internship-spec/blob/master/processes/process-new-mentor.md
https://github.com/cs-internship/cs-internship-spec/blob/master/processes/process-new-intern.md

**Comment by mehrandvd** [comment]
Thank you @Md23Mh and @ShahryarSaljoughi, I think it's great.
I'll merge the related pull requests and close this issue.
