### ISSUE TITLE
Update the content of step 3 in web course

### ISSUE THREAD

**Issue by maryamhdr** [cs-internship/cs-internship-spec#38]
The content of step 3 in web course has been redesigned and the [related doc](https://github.com/cs-internship/cs-internship-spec/blob/master/courses/web/03-Web-In-Practice-1-Client.md) needs to be updated.

**Comment by mehrandvd** [comment]
As we have redesigned the whole steps for the web, this issue doesn't apply anymore and I'm closing it.
