### ISSUE TITLE
Moving contents to the Wiki

### ISSUE THREAD

**Issue by amirhosseinab** [cs-internship/cs-internship-spec#4]
I think it's more appropriate to move all the contents of this repository to the Wiki.
And the root `README.md` should contain only the `TOC`,  and links to the wiki sections.

**Comment by mehrandvd** [comment]
As we are going to publish the `.md` file contents of this repo to a website, we can not move them to the Wiki.

While I'm closing this issue, please let me know if there is still some point that I missed.
