### ISSUE TITLE
typo in exercism section

### ISSUE THREAD

**Issue by alibalouchi** [cs-internship/cs-internship-spec#8]
in exercism section there is a typo instead of Panagarm you should write pangram
and for good looking you can put it like :
* exercism section:
    * Hello world
    * Two Fer
    * Pangram
    * Pascal's Triangle
    * Leap

#doc

**Comment by mehrandvd** [comment]
@ShahryarSaljoughi can you check this out and correct it?

**Comment by alibalouchi** [comment]
in last commit [https://github.com/cs-internship/cs-internship-spec/commit/36e400e41f555e5bdf8d0c159013563d747cd0d7] panagarm should be pangram

**Comment by ShahryarSaljoughi** [comment]
@alibalouchi  thank you for your help. it's corrected now.
